Neos:
    ContentRepository:
        contentDimensions:
            'language':
                label: 'KircheCom.SiteGenesis:General:contentDimensions.language'
                icon: 'icon-language'
                default: 'de'
                defaultPreset: 'de'
                presets:
                    'en':
                        label: 'English'
                        values: ['en']
                        uriSegment: 'en'
                    'de':
                        label: 'Deutsch'
                        values: ['de']
                        uriSegment: 'de'
    Flow:
        i18n:
            defaultLocale: de
            fallbackRule:
                order: ['en']
        mvc:
            routes:
                'Neos.Neos':
                    variables:
                        defaultUriSuffix: ''
    Neos:
        nodeTypes:
            groups:
                stainedGlass:
                    label: 'KircheCom.SiteGenesis:General:groups.stainedGlass'
        userInterface:
            defaultLanguage: de
            translation:
                autoInclude:
                    'KircheCom.SiteGenesis': ['General', 'NodeTypes/*']
Jonnitto:
    PrettyEmbedHelper:
        enableGdprMessage: true
    PrettyEmbedYoutube:
        url:
            playlist:
                embed: 'https://www.youtube-nocookie.com/embed/videoseries?list=%id%'
                href: 'https://www.youtube-nocookie.com/playlist?list=%id%'
            video:
                embed: 'https://www.youtube-nocookie.com/embed/%id%'
                href: 'https://www.youtube-nocookie.com/watch?v=%id%'
Sitegeist:
    Monocle:
        hiddenPrototypeNamePatterns:
            - 'Carbon.IncludeAssets:*'
            - 'Sitegeist.Kaleidoscope:*'
        preview:
            defaultPrototypeName: 'KircheCom.SiteGenesis:Component.Template.Base'
        ui:
            viewportPresets:
                xs: ~
                md: ~
                l: ~
                bootstrap-xs:
                    label: 'Extra Small'
                    width: 300
                    height: 800
                bootstrap-sm:
                    label: 'Small'
                    width: 576
                    height: 800
                bootstrap-md:
                    label: 'Medium'
                    width: 768
                    height: 800
                bootstrap-lg:
                    label: 'Large'
                    width: 992
                    height: 800
                bootstrap-xl:
                    label: 'Extra Large'
                    width: 1200
                    height: 800
